@hostname = api.example.com
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

###
#----------------

@name = hello

GET https://{{host}}/authors/{{name}} HTTP/1.1

###
#----------------

PATCH https://{{host}}/authors/{{name}} HTTP/1.1
Content-Type: {{contentType}}

{
    "content": "foo bar",
    "created_at": "{{createdAt}}",
    "modified_by": "{{modifiedBy}}"
}

### 2. Register the webhook
#--------------------------------------------------------------
POST https://payments.yoco.com/api/webhooks HTTP/1.1
Content-Type: application/json
Authorization: Bearer sk_test_a27f36bfRgzl33N218448d5b44ac

{
  "name": "celebrity-pulse",
  "url": "https://parseapi.back4app.com/functions/webhook-endpoint",
  "url": "https://aa0e-165-16-180-99.ngrok-free.app/webhook-endpoint"
}


### 2. Register the webhook
#--------------------------------------------------------------
